spring:
  application:
    name: backend
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      database: world_connect_db
      host: localhost
      port: 27017
  datasource:
    url: jdbc:mariadb://localhost:3306/world_connect_db?createDatabaseIfNotExist=true
    username: root
    password: 123456789
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update