spring:
  application:
    name: backend
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/worldconnect?createDatabaseIfNotExist=true
    username: root
    password: 123456789
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update